In [3]:
import pandas as pd
import numpy as np

In [4]:
path = 'ChurnData.csv'
df = pd.read_csv(path)
df

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,55.0,44.0,24.0,83.0,1.0,23.0,0.0,1.0,0.0,17.35,...,0.0,0.0,0.0,1.0,0.0,2.854,3.199,4.419,3.0,0.0
196,34.0,23.0,3.0,24.0,1.0,7.0,0.0,1.0,0.0,6.00,...,0.0,0.0,1.0,1.0,0.0,1.792,3.332,3.178,3.0,0.0
197,6.0,32.0,10.0,47.0,1.0,10.0,0.0,1.0,0.0,3.85,...,0.0,0.0,1.0,1.0,0.0,1.348,3.168,3.850,3.0,0.0
198,24.0,30.0,0.0,25.0,4.0,5.0,0.0,1.0,1.0,8.70,...,1.0,1.0,1.0,1.0,1.0,2.163,3.866,3.219,4.0,1.0
199,61.0,50.0,16.0,190.0,2.0,22.0,1.0,1.0,1.0,16.85,...,0.0,1.0,0.0,0.0,1.0,2.824,3.240,5.247,2.0,0.0

In [6]:
X = df.drop("churn",1)
Y = df["churn"]

In [7]:
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
cor = df.corr()

In [8]:
#Correlation with output variable
cor_target = abs(cor["churn"])
#Selecting highly correlated features
relevant_features = cor_target[cor_target>0.3]
relevant_features

tenure      0.376860
employ      0.337969
callcard    0.311451
loglong     0.336869
churn       1.000000
Name: churn, dtype: float64

In [9]:
X_new = df[["tenure", "employ", "callcard", "loglong"]]
featureset = X_new

from sklearn.preprocessing import MinMaxScaler
x = featureset.values #returns a numpy array
min_max_scaler = MinMaxScaler()
feature_mtx = min_max_scaler.fit_transform(x)
X_new = feature_mtx
X_new

array([[0.14084507, 0.11363636, 1.        , 0.34357196],
       [0.45070423, 0.        , 0.        , 0.5328214 ],
       [0.30985915, 0.04545455, 0.        , 0.43249938],
       [0.52112676, 0.22727273, 1.        , 0.42234332],
       [0.08450704, 0.34090909, 1.        , 0.46197672],
       [0.94366197, 0.54545455, 1.        , 0.72702502],
       [0.57746479, 0.18181818, 1.        , 0.49913302],
       [0.11267606, 0.04545455, 0.        , 0.24027743],
       [0.47887324, 0.47727273, 1.        , 0.44017835],
       [0.67605634, 0.43181818, 1.        , 0.60886797],
       [0.77464789, 0.27272727, 1.        , 0.77136487],
       [0.64788732, 0.27272727, 1.        , 0.71488729],
       [0.77464789, 0.54545455, 1.        , 0.80876889],
       [0.95774648, 0.52272727, 1.        , 0.81050285],
       [0.21126761, 0.11363636, 0.        , 0.42036165],
       [0.04225352, 0.13636364, 0.        , 0.27966312],
       [0.36619718, 0.25      , 0.        , 0.46197672],
       [0.71830986, 0.02272727, 1.        , 0.59722566],
       [0.88732394, 0.04545455, 1.        , 0.76418132],
       [0.15492958, 0.        , 1.        , 0.31979192],
       [0.47887324, 0.25      , 1.        , 0.53678474],
       [0.16901408, 0.04545455, 0.        , 0.41392123],
       [0.61971831, 0.        , 0.        , 0.54570225],
       [0.02816901, 0.06818182, 0.        , 0.1481298 ],
       [0.73239437, 0.        , 1.        , 0.59301461],
       [0.22535211, 0.13636364, 0.        , 0.41193956],
       [0.81690141, 0.5       , 1.        , 0.6239782 ],
       [0.78873239, 0.20454545, 1.        , 0.73990587],
       [0.02816901, 0.06818182, 1.        , 0.27594749],
       [0.04225352, 0.25      , 1.        , 0.20336884],
       [0.3943662 , 0.15909091, 1.        , 0.44017835],
       [0.88732394, 0.59090909, 1.        , 0.64726282],
       [0.29577465, 0.02272727, 0.        , 0.46197672],
       [0.45070423, 0.09090909, 0.        , 0.47560069],
       [0.23943662, 0.18181818, 1.        , 0.43423334],
       [0.90140845, 0.54545455, 1.        , 0.73297003],
       [0.53521127, 0.09090909, 1.        , 0.55660144],
       [0.38028169, 0.11363636, 0.        , 0.30047065],
       [0.63380282, 0.15909091, 1.        , 0.63462968],
       [0.5915493 , 0.40909091, 1.        , 0.52340847],
       [0.28169014, 0.04545455, 1.        , 0.34902155],
       [0.73239437, 0.15909091, 1.        , 0.48204112],
       [0.69014085, 0.36363636, 1.        , 0.59103295],
       [0.5915493 , 0.09090909, 0.        , 0.47882091],
       [0.45070423, 0.15909091, 1.        , 0.51523408],
       [0.61971831, 0.29545455, 1.        , 0.48377508],
       [0.38028169, 0.5       , 0.        , 0.32301214],
       [0.50704225, 0.27272727, 1.        , 0.66782264],
       [0.98591549, 0.68181818, 1.        , 0.63363884],
       [0.8028169 , 0.38636364, 0.        , 0.60217984],
       [0.49295775, 0.47727273, 1.        , 0.50656428],
       [0.35211268, 0.20454545, 1.        , 0.51102304],
       [0.16901408, 0.47727273, 1.        , 0.31037899],
       [0.38028169, 0.43181818, 0.        , 0.42036165],
       [0.        , 0.        , 0.        , 0.22244241],
       [0.1971831 , 0.18181818, 0.        , 0.38246222],
       [0.15492958, 0.13636364, 1.        , 0.30715878],
       [0.05633803, 0.15909091, 0.        , 0.33787466],
       [0.43661972, 0.02272727, 1.        , 0.398811  ],
       [0.18309859, 0.09090909, 0.        , 0.63116175],
       [0.92957746, 0.47727273, 1.        , 0.70398811],
       [0.83098592, 0.25      , 1.        , 0.60019817],
       [0.97183099, 0.54545455, 1.        , 0.79019074],
       [0.07042254, 0.11363636, 1.        , 0.34357196],
       [0.52112676, 0.        , 1.        , 0.56923458],
       [0.73239437, 0.11363636, 1.        , 0.67599703],
       [0.50704225, 0.47727273, 1.        , 0.47560069],
       [0.84507042, 0.29545455, 1.        , 0.69383205],
       [0.26760563, 0.06818182, 0.        , 0.48377508],
       [1.        , 0.45454545, 1.        , 0.96333911],
       [0.84507042, 0.13636364, 1.        , 0.77433738],
       [0.74647887, 0.13636364, 1.        , 0.60019817],
       [0.38028169, 0.15909091, 1.        , 0.60985881],
       [0.71830986, 0.18181818, 1.        , 0.71414417],
       [0.5915493 , 0.02272727, 1.        , 0.60515234],
       [0.63380282, 0.38636364, 1.        , 0.56923458],
       [0.53521127, 0.61363636, 0.        , 0.49764677],
       [0.12676056, 0.06818182, 0.        , 0.33787466],
       [0.95774648, 0.43181818, 1.        , 0.74040129],
       [0.61971831, 0.09090909, 1.        , 0.46197672],
       [0.71830986, 0.38636364, 1.        , 0.61852861],
       [0.57746479, 0.25      , 0.        , 0.45850879],
       [0.05633803, 0.36363636, 0.        , 0.35719594],
       [0.12676056, 0.20454545, 1.        , 0.46197672],
       [0.35211268, 0.02272727, 1.        , 0.4671786 ],
       [0.33802817, 0.09090909, 1.        , 0.50805053],
       [0.4084507 , 0.02272727, 1.        , 0.48848155],
       [0.90140845, 0.59090909, 1.        , 0.92172405],
       [0.05633803, 0.06818182, 0.        , 0.26455289],
       [0.08450704, 0.02272727, 1.        , 0.29725043],
       [0.33802817, 0.02272727, 0.        , 0.38716869],
       [0.09859155, 0.        , 1.        , 0.49145405],
       [0.53521127, 0.22727273, 0.        , 0.50061927],
       [0.38028169, 0.04545455, 1.        , 0.42234332],
       [0.76056338, 0.63636364, 1.        , 0.46024275],
       [0.14084507, 0.06818182, 0.        , 0.32895715],
       [0.70422535, 0.40909091, 1.        , 0.70844687],
       [0.33802817, 0.75      , 1.        , 0.50061927],
       [0.85915493, 0.40909091, 1.        , 0.68194204],
       [0.73239437, 0.13636364, 1.        , 0.68763934],
       [0.        , 0.06818182, 1.        , 0.        ],
       [0.26760563, 0.11363636, 0.        , 0.4530592 ],
       [0.46478873, 0.        , 1.        , 0.6353728 ],
       [0.6056338 , 0.47727273, 1.        , 0.59004211],
       [0.15492958, 0.        , 1.        , 0.26455289],
       [0.53521127, 0.06818182, 1.        , 0.5355462 ],
       [0.25352113, 0.        , 1.        , 0.47733465],
       [0.08450704, 0.04545455, 0.        , 0.29031459],
       [0.43661972, 0.22727273, 1.        , 0.47064652],
       [0.47887324, 0.22727273, 1.        , 0.62843696],
       [0.77464789, 0.11363636, 0.        , 0.84741144],
       [0.05633803, 0.13636364, 1.        , 0.24448848],
       [0.21126761, 0.65909091, 0.        , 0.30393857],
       [0.22535211, 0.04545455, 0.        , 0.49913302],
       [0.11267606, 0.02272727, 0.        , 0.48055487],
       [0.11267606, 0.06818182, 0.        , 0.35992073],
       [0.98591549, 0.52272727, 1.        , 0.83998018],
       [0.14084507, 0.06818182, 1.        , 0.32895715],
       [0.30985915, 0.18181818, 0.        , 0.49913302],
       [0.32394366, 0.11363636, 0.        , 0.48055487],
       [0.04225352, 0.04545455, 0.        , 0.26455289],
       [0.12676056, 0.02272727, 1.        , 0.42853604],
       [0.32394366, 0.13636364, 0.        , 0.27223186],
       [0.15492958, 0.09090909, 0.        , 0.30047065],
       [0.81690141, 0.47727273, 1.        , 0.51944513],
       [1.        , 0.13636364, 1.        , 0.87292544],
       [0.92957746, 0.25      , 1.        , 0.79291553],
       [0.12676056, 0.13636364, 0.        , 0.37750805],
       [0.4084507 , 0.18181818, 0.        , 0.60019817],
       [0.32394366, 0.13636364, 1.        , 0.59301461],
       [1.        , 1.        , 1.        , 0.94203617],
       [0.35211268, 0.09090909, 0.        , 0.48848155],
       [0.49295775, 0.34090909, 0.        , 0.55883081],
       [0.21126761, 0.65909091, 1.        , 0.45677483],
       [0.74647887, 0.04545455, 1.        , 0.6353728 ],
       [1.        , 0.70454545, 1.        , 0.80505326],
       [0.25352113, 0.11363636, 1.        , 0.38716869],
       [0.23943662, 0.15909091, 1.        , 0.27223186],
       [0.61971831, 0.        , 0.        , 0.44191231],
       [0.22535211, 0.06818182, 1.        , 0.12212039],
       [0.09859155, 0.38636364, 0.        , 0.42432499],
       [0.91549296, 0.09090909, 1.        , 0.8518702 ],
       [0.83098592, 0.68181818, 1.        , 0.72281397],
       [0.87323944, 0.20454545, 1.        , 0.64651969],
       [0.61971831, 0.04545455, 0.        , 0.62026257],
       [0.94366197, 0.27272727, 1.        , 0.77978697],
       [0.07042254, 0.11363636, 0.        , 0.33192965],
       [0.97183099, 0.20454545, 1.        , 0.911568  ],
       [0.32394366, 0.        , 1.        , 0.5613079 ],
       [0.25352113, 0.11363636, 1.        , 0.29725043],
       [0.05633803, 0.38636364, 1.        , 0.40104038],
       [0.18309859, 0.25      , 1.        , 0.43621501],
       [0.22535211, 0.22727273, 0.        , 0.51102304],
       [0.81690141, 0.11363636, 1.        , 0.81223681],
       [0.83098592, 0.84090909, 1.        , 0.54446371],
       [0.73239437, 0.04545455, 1.        , 0.39410453],
       [0.18309859, 0.        , 0.        , 0.34357196],
       [0.22535211, 0.        , 0.        , 0.46197672],
       [0.95774648, 0.        , 1.        , 0.78300718],
       [0.12676056, 0.        , 0.        , 0.41615061],
       [0.28169014, 0.02272727, 1.        , 0.42630666],
       [0.88732394, 0.20454545, 1.        , 0.66559326],
       [0.83098592, 0.25      , 1.        , 0.65147387],
       [0.8028169 , 0.18181818, 1.        , 0.56601437],
       [1.        , 0.18181818, 1.        , 0.79613574],
       [0.23943662, 0.31818182, 1.        , 0.43819668],
       [0.97183099, 0.34090909, 1.        , 0.72529106],
       [0.08450704, 0.09090909, 1.        , 0.31037899],
       [0.98591549, 0.        , 1.        , 0.85682437],
       [0.42253521, 0.29545455, 1.        , 0.47882091],
       [0.21126761, 0.11363636, 0.        , 0.32598464],
       [0.81690141, 0.02272727, 1.        , 0.60515234],
       [0.11267606, 0.15909091, 1.        , 0.27594749],
       [0.15492958, 0.11363636, 0.        , 0.41813228],
       [0.02816901, 0.25      , 1.        , 0.22714887],
       [0.71830986, 0.40909091, 1.        , 0.55883081],
       [0.23943662, 0.38636364, 0.        , 0.31037899],
       [0.5915493 , 0.29545455, 1.        , 0.74263067],
       [0.50704225, 0.18181818, 0.        , 0.52613327],
       [0.70422535, 0.47727273, 1.        , 0.68268516],
       [0.77464789, 0.31818182, 1.        , 0.63289571],
       [1.        , 0.56818182, 1.        , 1.        ],
       [0.43661972, 0.54545455, 1.        , 0.48055487],
       [0.70422535, 0.36363636, 1.        , 0.65865742],
       [0.35211268, 0.59090909, 1.        , 0.33490216],
       [0.46478873, 0.20454545, 1.        , 0.41813228],
       [0.26760563, 0.        , 1.        , 0.35174635],
       [0.8028169 , 0.18181818, 1.        , 0.66930889],
       [0.33802817, 0.43181818, 1.        , 0.56006936],
       [0.91549296, 0.54545455, 1.        , 0.55412435],
       [0.98591549, 0.43181818, 1.        , 0.82635621],
       [0.07042254, 0.        , 1.        , 0.13549666],
       [0.35211268, 0.15909091, 0.        , 0.5328214 ],
       [0.84507042, 0.40909091, 1.        , 0.59400545],
       [0.78873239, 0.61363636, 1.        , 0.66485014],
       [0.76056338, 0.52272727, 1.        , 0.68342829],
       [0.46478873, 0.15909091, 1.        , 0.42036165],
       [0.07042254, 0.22727273, 1.        , 0.31037899],
       [0.32394366, 0.11363636, 1.        , 0.51226158],
       [0.84507042, 0.5       , 1.        , 0.67599703]])

In [10]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 2, max_iter=50000)
kmeans
kModel = kmeans.fit(X_new)

In [11]:
pd.crosstab(Y, kModel.labels_)

col_0    0   1
churn
0.0    113  29
1.0     28  30

In [12]:
(113 + 30) / (113 + 30 + 29 + 28)

0.715

In [13]:
from sklearn.datasets import load_iris
df.describe()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
count,200.000000,200.000000,200.000000,200.000000,200.00000,200.00000,200.000000,200.000000,200.000000,200.00000,...,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,35.505000,41.165000,11.650000,75.130000,2.82500,10.22500,0.425000,0.705000,0.290000,11.78925,...,0.275000,0.440000,0.45500,0.460000,0.440000,2.193285,3.229185,3.951015,2.475000,0.290000
std,21.640971,13.076803,10.158419,128.430468,1.28555,8.95743,0.495584,0.457187,0.454901,9.88725,...,0.447635,0.497633,0.49922,0.499648,0.497633,0.731282,0.281019,0.752553,1.079445,0.454901
min,1.000000,19.000000,0.000000,9.000000,1.00000,0.00000,0.000000,0.000000,0.000000,1.10000,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.095000,1.749000,2.197000,1.000000,0.000000
25%,16.750000,31.000000,3.000000,31.000000,2.00000,3.00000,0.000000,0.000000,0.000000,5.53750,...,0.000000,0.000000,0.00000,0.000000,0.000000,1.711750,3.226500,3.434000,2.000000,0.000000
50%,33.500000,40.000000,9.000000,48.000000,3.00000,7.50000,0.000000,1.000000,0.000000,8.25000,...,0.000000,0.000000,0.00000,0.000000,0.000000,2.110000,3.240000,3.871000,2.000000,0.000000
75%,55.250000,51.000000,18.000000,80.000000,4.00000,17.00000,1.000000,1.000000,1.000000,14.30000,...,1.000000,1.000000,1.00000,1.000000,1.000000,2.660000,3.240000,4.382000,3.000000,1.000000
max,72.000000,76.000000,48.000000,1668.000000,5.00000,44.00000,1.000000,1.000000,1.000000,62.30000,...,1.000000,1.000000,1.00000,1.000000,1.000000,4.132000,4.227000,7.419000,4.000000,1.000000

In [14]:
inp_data = df[df.columns[:-1]]
inp_data

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,voice,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,1.0,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,55.0,44.0,24.0,83.0,1.0,23.0,0.0,1.0,0.0,17.35,...,0.0,0.0,0.0,0.0,1.0,0.0,2.854,3.199,4.419,3.0
196,34.0,23.0,3.0,24.0,1.0,7.0,0.0,1.0,0.0,6.00,...,0.0,0.0,0.0,1.0,1.0,0.0,1.792,3.332,3.178,3.0
197,6.0,32.0,10.0,47.0,1.0,10.0,0.0,1.0,0.0,3.85,...,0.0,0.0,0.0,1.0,1.0,0.0,1.348,3.168,3.850,3.0
198,24.0,30.0,0.0,25.0,4.0,5.0,0.0,1.0,1.0,8.70,...,1.0,1.0,1.0,1.0,1.0,1.0,2.163,3.866,3.219,4.0
199,61.0,50.0,16.0,190.0,2.0,22.0,1.0,1.0,1.0,16.85,...,0.0,0.0,1.0,0.0,0.0,1.0,2.824,3.240,5.247,2.0

In [15]:
out_data = [df['custcat']]
out_data

[0      4.0
 1      1.0
 2      3.0
 3      4.0
 4      3.0
       ...
 195    3.0
 196    3.0
 197    3.0
 198    4.0
 199    2.0
 Name: custcat, Length: 200, dtype: float64]

In [16]:
from sklearn.cluster import KMeans

In [17]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 4, max_iter=100000)
kmeans
kModel = kmeans.fit(inp_data)

In [18]:
kModel = kmeans.fit(inp_data)

In [19]:
kModel.labels_

array([1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 2, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0,
       1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 3, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1,
       1, 2])

In [20]:
pd.crosstab(out_data, kModel.labels_)

col_0     0   1   2  3
custcat
1.0       0  42   3  0
2.0       3  42  14  2
3.0      11  34   3  0
4.0      16  28   2  0

In [20]:
(238+53) / (31+ 234 + 1+ 34 + 179 + 1 + 3 + 53 + 215 + 2 + 11 + 44 + 181 + 1 + 10)

0.291